const express = require('express')
const app = express()
const dotenv = require('dotenv').config()
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const auth = require('./routers/auth')
const cors = require('cors')
const connectdb = require('./db/database')
app.use(cors())
app.use(bodyParser.json())
app.use(express.json())
app.use('/api/auth', auth)
app.listen(4000, () => {
  console.log(4000)
  connectdb()
})
